language: php

env:
  - APP_ENV=travis
php:
  - 5.5
  - 5.6
  - hhvm
install: 
  - ./tests/install.sh
before_script:
  - composer self-update
  - composer install --dev
  - composer update
script: 
    - phpunit 
